// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfnywhoyfognsdypbrtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmbnl3aG95Zm9nbnNkeXBicnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MDQ5NzEsImV4cCI6MjA5MDQ4MDk3MX0.AxWcz53YQ16lAEJqKWI_6hhk2BnkriD4nixxq2dWQdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});